### ISSUE TITLE
Fullname

### ISSUE THREAD

**Issue by FabioZTessitore** [MarcoDaniello/helloworld_c#2]
Aggiusta. Devi stampare su una sola riga

**Comment by FabioZTessitore** [comment]
Hai provato a mandarlo in esecuzione haha?

**Comment by MarcoDaniello** [comment]
professore ho aggiustato, ma comunque non mi fa compilare. Dice: fullname.c:1:19: fatal error : stdio.h : file o directory non esistente compilation terminated

**Comment by FabioZTessitore** [comment]
Che linux usi?

Il 22 apr 2017 3:08 PM, "MarcoDaniello" <notifications@github.com> ha
scritto:

**Comment by MarcoDaniello** [comment]
mint cinnamon

**Comment by FabioZTessitore** [comment]
Installa il pacchetto build-essentials

Il 22 apr 2017 3:13 PM, "Fabio Z Tessitore" <fabioztessitore@gmail.com> ha
scritto:

**Comment by MarcoDaniello** [comment]
ok, risolto
