### ISSUE TITLE
cerchio

### ISSUE THREAD

**Issue by FabioZTessitore** [MarcoDaniello/helloworld_c#6]
questo non hai provato proprio a compilarlo ...

**Comment by MarcoDaniello** [comment]
Perchè??

**Comment by FabioZTessitore** [comment]
perché è evidentemente pieno di errori di sintassi, non fare il furbo

**Comment by MarcoDaniello** [comment]
Quando l'ho compilato, andava...

Il 04 Feb 2018 21:12, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
ma i risultati come sono?
